set_property PACKAGE_PIN U14 [get_ports clk]
create_clock -period 10.000 -name clk [get_ports clk]

set_property PACKAGE_PIN N17 [get_ports matched_filter_valid]
set_property PACKAGE_PIN P14 [get_ports {matched_filter_out[7]}]
set_property PACKAGE_PIN P15 [get_ports {matched_filter_out[6]}]
set_property PACKAGE_PIN P16 [get_ports {matched_filter_out[5]}]
set_property PACKAGE_PIN P18 [get_ports {matched_filter_out[4]}]
set_property PACKAGE_PIN R16 [get_ports {matched_filter_out[3]}]
set_property PACKAGE_PIN R18 [get_ports {matched_filter_out[2]}]
set_property PACKAGE_PIN R19 [get_ports {matched_filter_out[1]}]
set_property PACKAGE_PIN T14 [get_ports {matched_filter_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports matched_filter_valid]
set_property IOSTANDARD LVCMOS33 [get_ports resetn]
set_property IOSTANDARD LVCMOS33 [get_ports {matched_filter_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {matched_filter_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {matched_filter_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {matched_filter_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {matched_filter_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {matched_filter_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {matched_filter_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {matched_filter_out[0]}]
set_property PACKAGE_PIN T15 [get_ports resetn]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

